StanfordSpezi/spezi-web-design-system

src/components/Button/ButtonPending.tsx

Pending button icon is not vertically centered.
* Center icon of pending Button
Fixed `isPending` state:

Center isPending icon of Button

---

src/components/Tooltip/Tooltip.tsx
src/forms/Field/Field.stories.tsx
src/forms/Field/Field.test.tsx
src/forms/Field/Field.tsx
src/forms/Field/FieldTooltip.tsx

Fields sometimes need more explanation about their purpose or details. Tooltips are useful for that. 
* Add Field tooltip

Add Field tooltip

---

package-lock.json
package.json

Publish fails if there is package.json, because `publishpackage` action tries to set version.

Remove version from package.json

---

src/modules/auth/user.test.ts
src/modules/auth/user.ts

Sometimes, `displayName` might be `""`. We want to make sure `getUserName` tries to provide whatever is renderable out of user object.
* Prevent returning empty string from getUserName function

Prevent returning empty string from getUserName function

---

package.json
src/index.ts
src/utils/data/data.test.ts
src/utils/data/data.ts
src/utils/data/index.ts

Sometimes there is a need to perform bulk-operation on data, comparing previous set and new set to verify what operations are necessary. This is a helper for that situation. 
* Add syncData helper

Add syncData helper

---

src/components/Calendar/Calendar.test.tsx

`Calendar` tests are failing due to short month of February. In order to fix it, make sure displayed month is the same as `selected` date.
* Fix flaky Calendar tests

Fix flaky Calendar tests

---

src/molecules/DashboardLayout/DashboardContext.tsx
src/molecules/DashboardLayout/DashboardLayout.stories.tsx
src/molecules/DashboardLayout/DashboardLayout.tsx
src/molecules/DashboardLayout/MenuItem.tsx
src/molecules/DashboardLayout/UserMenuItem.tsx

`DashboardLayout` shrinks on smaller desktop screens to preserve more space. This works well for pure menus with icons, but doesn't if aside contains something else than `MenuLink`. 
* Add non-shrinkable variant of Dashboard
`shrinkable={false}` property
* Fix hiding header. 
If there is no title and actions, hide header, but only on desktops. On mobile screens we still need it to open menu.
https://github.com/user-attachments/assets/e14b57cf-71fb-4de5-b11d-859071e459ed

Add non-shrinkable variant of Dashboard

---

package-lock.json
package.json
src/components/InputOTP/InputOTP.stories.tsx
src/components/InputOTP/InputOTP.test.tsx
src/components/InputOTP/InputOTP.tsx
src/components/InputOTP/index.tsx
src/index.ts

InputOTP is useful for handling one time passwords, confirmation codes and secrets.
* Add InputOTP component
```ts
<InputOTP
maxLength={8}
onComplete={(code: string) => {}}
/>
```

Add InputOTP component

---

package.json
src/components/Skeleton/Skeleton.stories.tsx
src/components/Skeleton/Skeleton.test.tsx
src/components/Skeleton/Skeleton.tsx
src/components/Skeleton/index.tsx
src/index.ts

`Skeleton` is a loading state pattern that allows rendering "loader" in a shape of the actual content, to prevent layout shifts.
* Add "Skeleton" component
https://github.com/user-attachments/assets/1bcca124-94c8-462d-b9f5-12c670b40183

Add Skeleton component

---

src/components/DataTable/DataTable.stories.tsx
src/components/DataTable/DataTable.test.tsx
src/components/DataTable/DataTable.tsx

`DataTable` handles empty props internally. This PR adds way to customize default DataTable approach.
* Add customizable empty state to DataTable
* Add more state stories
* Restructure empty state tests

Make empty state of DataTable customizable

---

src/components/DatePicker/DatePicker.tsx
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.test.tsx
src/components/Popover/Popover.tsx

Popover was very basic compared to Dialog. Since they can serve similar purpose, I added similar tooling around Popover as in the Dialog. 
* Add arrow to Popover
* Add PopoverTitle, PopoverDescription,PopoverCloseX components
https://github.com/user-attachments/assets/6a9766f9-061f-4c25-a260-0548c0b61c40

Add new elements to Popover component

---

src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/Dialog.tsx
src/utils/tailwind/helpers.ts

Currently changing Dialog size requires overwriting default `max-w-lg`. Dialog size change is quite common operation, so it's handy to create and surface special prop for that
* Create Tailwind size helpers
* Add `size` prop to Dialog
* Add stories for size dialogs
https://github.com/user-attachments/assets/9597e43f-3691-4452-9252-dc3eca246dab

Add different Dialog sizes

---

src/components/Label/Label.tsx
src/forms/Field/Field.stories.tsx
src/forms/Field/Field.tsx

Sometimes there is a need to customize label rendering, by adding new properties, but keeping standard label<->form field distance and gaps between label elements. Exposed `LabelContainer` allows that.
* Expose LabelContainer as separate component
Nothing changed implementation wise.
**Custom Label Elements** story

Expose LabelContainer as separate component

---

src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx
src/tailwind.css
src/theme/light.ts
src/theme/utils.ts

Primary role of a Badge is to represent statuses. We need to cover common scenarios like `warning` or `success` status. 
* Add success and destructive colors to the theme
* Add success and warning Badge variant
Tested visually through Storybook.

Add `success` and `warning` Badge variants

---

package.json
src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Accordion.test.tsx
src/components/Accordion/Accordion.tsx
src/components/Accordion/index.ts
src/components/Collapsible/Collapsible.stories.tsx
src/components/Collapsible/Collapsible.test.tsx
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/index.ts
src/index.ts

It's hard to create accessible and performantly animated collapsible UI element. This PR provides:
* `Collapsible` as primitive component for rendering collapsibles
* `Accordion` as ready UI element to render list of items that can be accorded with 
* Add `Collapsible` component
* Add `Accordion` component
https://github.com/user-attachments/assets/2a0f0df7-d416-4a69-86d9-d0f4076a8fba

Add `Collapsible` and `Accordion` components

---

src/utils/dev/dev.ts

Initially `any` was placed there to simplify usage by allowing to use `notImplemented` and `notImplementedAlert` in place of `any` function. However, with our strict TypeScript linters, it results with errors. In order to actually make it simpler to use, it should be better to simplify satisfy the return type needs of a function that is mocked with `notImplemented` or `notImplementedAlert`. 
* Remove `any` from dev helpers

Remove `any` from dev helpers

---

src/components/Badge/Badge.tsx
src/components/Button/Button.tsx
src/components/DropdownMenu/DropdownMenu.tsx
src/components/Table/Table.tsx
src/tailwind.css

`transition` is better for reusability than specific transition types like `transition-color`. If consumer wants to modify something inside the component, they're more free to do so.
* Replace specified transition classes with general purpose transition
* `transition-all` are kept as is, because those are more specific cases. 

Replace specified transition classes with general purpose transition

---

src/components/DataTable/DataTable.tsx

`DataTable` header can be extended with custom elements through `header` prop. In such scenarios, we need to make sure that there is at least minimal amount of gap to prevent clashing on smaller screens and guarantee standard visual safety. 
* Add gap to DataTable header
* Tested manually
* Storybooks for header already exist

Add gap to DataTable header

---

package.json
src/index.ts
src/utils/useIsScrolled/index.ts
src/utils/useIsScrolled/useIsScrolled.test.ts
src/utils/useIsScrolled/useIsScrolled.ts

We need a hook that tracks whether the user has scrolled past a specified threshold.
Added a new hook in `src/utils/useIsScrolled/useIsScrolled.ts` that tracks whether the user has scrolled past a given threshold. The hook uses `useState` and `useEffect` to monitor scroll events and provides a boolean value (`true` if scrolled past the threshold).
Created a test suite in `src/utils/useIsScrolled/useIsScrolled.test.ts` to validate the behavior of the `useIsScrolled` hook. Tests cover various scenarios, including initial states, custom thresholds, state updates, and proper cleanup of event listeners.
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing …

Add `useIsScrolled` hook

---

src/components/Avatar/Avatar.stories.tsx
src/components/Avatar/Avatar.test.tsx
src/components/Avatar/Avatar.tsx

Right now, there is no way to add children to the `<Avatar />` component. So if you wanted to add something like a `<Badge />` to the `<Avatar />`, you would need to add a wrapping `<div>` to do proper relative alignment.
* Added a new `overlay` prop to the `Avatar` component, allowing users to render custom overlay content (e.g., badges or status indicators) positioned absolutely within the avatar container.
* Updated the `avatarVariance` styles to ensure proper positioning and overflow handling for the overlay. 
* Added an example of using the `overlay` prop in the `Avatar` component's JSDoc comments, demonstrating how to include a status badge.
* Introduced a new story, `WithOverlay`, in the `Avatar.stories.tsx` file to showcase the overlay functionality in Storybook.
Added a new test …

Add overlay prop to Avatar component

---

src/components/DropdownMenu/DropdownMenu.tsx

The DropdownMenu component has no shadow.
Added the `shadow-md` class to the `DropdownMenuContent` component.
Not needed.

Add shadow to dropdown menu

---

src/components/Async/Async.stories.tsx
src/components/Async/Async.tsx

Sometimes `Async` needs padding to be disabled. 
* Pass padding through an Async component to StateContainer

Pass padding through an Async component to StateContainer

---

src/utils/misc/misc.test.ts
src/utils/misc/misc.ts

Some utils from the study platform could be useful in this repo.
* Added the `Prettify` type in `misc.ts` to flatten complex intersection types, making them easier to read in tooling and type inspection.
* Added `joinPaths` function to `misc.ts`, which joins path segments while handling leading/trailing slashes, supports strings and numbers, and ignores empty/null/undefined segments.
Added unit tests for `joinPaths` in `misc.test.ts`, covering various edge cases such as duplicate slashes, absolute URLs, query/hash preservation, and numeric segments. 
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CON …

Add helpers from the study platform

---

src/components/Separator/DashedSeparator/DashedSeparator.tsx

The background color class of the `DashedSeparator` component is not picked up by Tailwind, if there is no 'border' color variable in the Tailwind config. Mysteriously, the styles are also not applied if there is a "--color-border" variable in a Tailwind v4 project.
Try for yourself: https://play.tailwindcss.com/YvxAVGZVFZ
Added a CSS variable (`--default-border-color`) to ensure the application of the `DashedSeparator` background color class is not dependent on successful parsing of `theme(colors.border)`
Made sure that the style is still applied correctly in the storyboard setup and that this solution works in Tailwind v4.
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and …

Make DashedSeparator styles more robust
